// tslint:disable
// eslint-disable
/**
 * PaulExpress API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DogGridDto
 */
export interface DogGridDto {
  /**
   *
   * @type {number}
   * @memberof DogGridDto
   */
  dogId?: number;
  /**
   *
   * @type {string}
   * @memberof DogGridDto
   */
  firstName?: string | null;
  /**
   *
   * @type {string}
   * @memberof DogGridDto
   */
  lastName?: string | null;
  /**
   *
   * @type {Date}
   * @memberof DogGridDto
   */
  dateOfBirth?: Date;
  /**
   *
   * @type {number}
   * @memberof DogGridDto
   */
  colorId?: number | null;
  /**
   *
   * @type {number}
   * @memberof DogGridDto
   */
  raceId?: number | null;
}

export function DogGridDtoFromJSON(json: any): DogGridDto {
  return DogGridDtoFromJSONTyped(json, false);
}

export function DogGridDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DogGridDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    dogId: !exists(json, "dogId") ? undefined : json["dogId"],
    firstName: !exists(json, "firstName") ? undefined : json["firstName"],
    lastName: !exists(json, "lastName") ? undefined : json["lastName"],
    dateOfBirth: !exists(json, "dateOfBirth") ? undefined : new Date(json["dateOfBirth"]),
    colorId: !exists(json, "colorId") ? undefined : json["colorId"],
    raceId: !exists(json, "raceId") ? undefined : json["raceId"]
  };
}

export function DogGridDtoToJSON(value?: DogGridDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    dogId: value.dogId,
    firstName: value.firstName,
    lastName: value.lastName,
    dateOfBirth: value.dateOfBirth === undefined ? undefined : value.dateOfBirth.toISOString(),
    colorId: value.colorId,
    raceId: value.raceId
  };
}
