// tslint:disable
// eslint-disable
/**
 * PaulExpress API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  DateSearch,
  DateSearchFromJSON,
  DateSearchFromJSONTyped,
  DateSearchToJSON,
  Int32ListSearch,
  Int32ListSearchFromJSON,
  Int32ListSearchFromJSONTyped,
  Int32ListSearchToJSON,
  TextSearch,
  TextSearchFromJSON,
  TextSearchFromJSONTyped,
  TextSearchToJSON
} from "./";

/**
 *
 * @export
 * @interface DogSearch
 */
export interface DogSearch {
  /**
   *
   * @type {TextSearch}
   * @memberof DogSearch
   */
  firstName?: TextSearch;
  /**
   *
   * @type {TextSearch}
   * @memberof DogSearch
   */
  lastName?: TextSearch;
  /**
   *
   * @type {DateSearch}
   * @memberof DogSearch
   */
  dateOfBirth?: DateSearch;
  /**
   *
   * @type {Int32ListSearch}
   * @memberof DogSearch
   */
  colorId?: Int32ListSearch;
  /**
   *
   * @type {Int32ListSearch}
   * @memberof DogSearch
   */
  raceId?: Int32ListSearch;
  /**
   *
   * @type {number}
   * @memberof DogSearch
   */
  pageNumber?: number;
  /**
   *
   * @type {number}
   * @memberof DogSearch
   */
  pageSize?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof DogSearch
   */
  sortKey?: Array<string> | null;
  /**
   *
   * @type {number}
   * @memberof DogSearch
   */
  readonly skipCount?: number;
  /**
   *
   * @type {number}
   * @memberof DogSearch
   */
  forceSkip?: number | null;
  /**
   *
   * @type {number}
   * @memberof DogSearch
   */
  forceTake?: number | null;
}

export function DogSearchFromJSON(json: any): DogSearch {
  return DogSearchFromJSONTyped(json, false);
}

export function DogSearchFromJSONTyped(json: any, ignoreDiscriminator: boolean): DogSearch {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    firstName: !exists(json, "firstName") ? undefined : TextSearchFromJSON(json["firstName"]),
    lastName: !exists(json, "lastName") ? undefined : TextSearchFromJSON(json["lastName"]),
    dateOfBirth: !exists(json, "dateOfBirth") ? undefined : DateSearchFromJSON(json["dateOfBirth"]),
    colorId: !exists(json, "colorId") ? undefined : Int32ListSearchFromJSON(json["colorId"]),
    raceId: !exists(json, "raceId") ? undefined : Int32ListSearchFromJSON(json["raceId"]),
    pageNumber: !exists(json, "pageNumber") ? undefined : json["pageNumber"],
    pageSize: !exists(json, "pageSize") ? undefined : json["pageSize"],
    sortKey: !exists(json, "sortKey") ? undefined : json["sortKey"],
    skipCount: !exists(json, "skipCount") ? undefined : json["skipCount"],
    forceSkip: !exists(json, "forceSkip") ? undefined : json["forceSkip"],
    forceTake: !exists(json, "forceTake") ? undefined : json["forceTake"]
  };
}

export function DogSearchToJSON(value?: DogSearch | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    firstName: TextSearchToJSON(value.firstName),
    lastName: TextSearchToJSON(value.lastName),
    dateOfBirth: DateSearchToJSON(value.dateOfBirth),
    colorId: Int32ListSearchToJSON(value.colorId),
    raceId: Int32ListSearchToJSON(value.raceId),
    pageNumber: value.pageNumber,
    pageSize: value.pageSize,
    sortKey: value.sortKey,
    forceSkip: value.forceSkip,
    forceTake: value.forceTake
  };
}
