// tslint:disable
// eslint-disable
/**
 * PaulExpress API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface EmployeeDto
 */
export interface EmployeeDto {
  /**
   *
   * @type {number}
   * @memberof EmployeeDto
   */
  employeeId?: number;
  /**
   *
   * @type {string}
   * @memberof EmployeeDto
   */
  firstName?: string | null;
  /**
   *
   * @type {string}
   * @memberof EmployeeDto
   */
  lastName?: string | null;
  /**
   *
   * @type {Date}
   * @memberof EmployeeDto
   */
  dateOfBirth?: Date;
  /**
   *
   * @type {string}
   * @memberof EmployeeDto
   */
  phoneNumber?: string | null;
  /**
   *
   * @type {string}
   * @memberof EmployeeDto
   */
  email?: string | null;
  /**
   *
   * @type {Date}
   * @memberof EmployeeDto
   */
  createdOn?: Date;
  /**
   *
   * @type {string}
   * @memberof EmployeeDto
   */
  createdBy?: string | null;
  /**
   *
   * @type {Date}
   * @memberof EmployeeDto
   */
  updatedOn?: Date;
  /**
   *
   * @type {string}
   * @memberof EmployeeDto
   */
  updatedBy?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof EmployeeDto
   */
  active?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof EmployeeDto
   */
  nullableActive?: boolean | null;
  /**
   *
   * @type {Date}
   * @memberof EmployeeDto
   */
  nullableDate?: Date | null;
}

export function EmployeeDtoFromJSON(json: any): EmployeeDto {
  return EmployeeDtoFromJSONTyped(json, false);
}

export function EmployeeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmployeeDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    employeeId: !exists(json, "employeeId") ? undefined : json["employeeId"],
    firstName: !exists(json, "firstName") ? undefined : json["firstName"],
    lastName: !exists(json, "lastName") ? undefined : json["lastName"],
    dateOfBirth: !exists(json, "dateOfBirth") ? undefined : new Date(json["dateOfBirth"]),
    phoneNumber: !exists(json, "phoneNumber") ? undefined : json["phoneNumber"],
    email: !exists(json, "email") ? undefined : json["email"],
    createdOn: !exists(json, "createdOn") ? undefined : new Date(json["createdOn"]),
    createdBy: !exists(json, "createdBy") ? undefined : json["createdBy"],
    updatedOn: !exists(json, "updatedOn") ? undefined : new Date(json["updatedOn"]),
    updatedBy: !exists(json, "updatedBy") ? undefined : json["updatedBy"],
    active: !exists(json, "active") ? undefined : json["active"],
    nullableActive: !exists(json, "nullableActive") ? undefined : json["nullableActive"],
    nullableDate: !exists(json, "nullableDate")
      ? undefined
      : json["nullableDate"] === null
      ? null
      : new Date(json["nullableDate"])
  };
}

export function EmployeeDtoToJSON(value?: EmployeeDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    employeeId: value.employeeId,
    firstName: value.firstName,
    lastName: value.lastName,
    dateOfBirth: value.dateOfBirth === undefined ? undefined : value.dateOfBirth.toISOString(),
    phoneNumber: value.phoneNumber,
    email: value.email,
    createdOn: value.createdOn === undefined ? undefined : value.createdOn.toISOString(),
    createdBy: value.createdBy,
    updatedOn: value.updatedOn === undefined ? undefined : value.updatedOn.toISOString(),
    updatedBy: value.updatedBy,
    active: value.active,
    nullableActive: value.nullableActive,
    nullableDate:
      value.nullableDate === undefined
        ? undefined
        : value.nullableDate === null
        ? null
        : value.nullableDate.toISOString()
  };
}
