// tslint:disable
// eslint-disable
/**
 * PaulExpress API v1.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  ECriteriaType,
  ECriteriaTypeFromJSON,
  ECriteriaTypeFromJSONTyped,
  ECriteriaTypeToJSON,
  EListSearchType,
  EListSearchTypeFromJSON,
  EListSearchTypeFromJSONTyped,
  EListSearchTypeToJSON
} from "./";

/**
 *
 * @export
 * @interface Int32ListSearch
 */
export interface Int32ListSearch {
  /**
   *
   * @type {ECriteriaType}
   * @memberof Int32ListSearch
   */
  typeOfCriteria?: ECriteriaType;
  /**
   *
   * @type {EListSearchType}
   * @memberof Int32ListSearch
   */
  searchMode?: EListSearchType;
  /**
   *
   * @type {number}
   * @memberof Int32ListSearch
   */
  value?: number;
  /**
   *
   * @type {number}
   * @memberof Int32ListSearch
   */
  secondaryValue?: number;
  /**
   *
   * @type {Array<string>}
   * @memberof Int32ListSearch
   */
  readonly availableSearchTypes?: Array<string> | null;
  /**
   *
   * @type {string}
   * @memberof Int32ListSearch
   */
  readonly currentSearchType?: string | null;
  /**
   *
   * @type {boolean}
   * @memberof Int32ListSearch
   */
  manualSearch?: boolean;
}

export function Int32ListSearchFromJSON(json: any): Int32ListSearch {
  return Int32ListSearchFromJSONTyped(json, false);
}

export function Int32ListSearchFromJSONTyped(json: any, ignoreDiscriminator: boolean): Int32ListSearch {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    typeOfCriteria: !exists(json, "typeOfCriteria") ? undefined : ECriteriaTypeFromJSON(json["typeOfCriteria"]),
    searchMode: !exists(json, "searchMode") ? undefined : EListSearchTypeFromJSON(json["searchMode"]),
    value: !exists(json, "value") ? undefined : json["value"],
    secondaryValue: !exists(json, "secondaryValue") ? undefined : json["secondaryValue"],
    availableSearchTypes: !exists(json, "availableSearchTypes") ? undefined : json["availableSearchTypes"],
    currentSearchType: !exists(json, "currentSearchType") ? undefined : json["currentSearchType"],
    manualSearch: !exists(json, "manualSearch") ? undefined : json["manualSearch"]
  };
}

export function Int32ListSearchToJSON(value?: Int32ListSearch | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    typeOfCriteria: ECriteriaTypeToJSON(value.typeOfCriteria),
    searchMode: EListSearchTypeToJSON(value.searchMode),
    value: value.value,
    secondaryValue: value.secondaryValue,
    manualSearch: value.manualSearch
  };
}
